name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.3.0
        pip install -r requirements.txt
    
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name=SalesDashboard --add-data="shapefiles;shapefiles" --hidden-import=streamlit --hidden-import=geopandas --hidden-import=plotly --hidden-import=pandas --hidden-import=shapely --hidden-import=fiona --hidden-import=pyproj --console app.py
    
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: SalesDashboard-Windows
        path: dist/SalesDashboard.exe
        retention-days: 90
